RA-03
4meech/RecipeApp pull request #1
Opened 2024-07-21 17:05 UTC by 4meech

Что-то совсем туго пошло. Приложение даже и запускаться не хочет. 

Откуда учитывать нижний отступ для контейнера с кнопками - от края макета или от навбара? Как включить его (навбара) отображение?

Атрибуты в стиле StyleNavButton android:paddingVertical и android:paddingHorizontal — для внутренних отступов. Не пойму как ими пользоваться. 

Размеры основного отступа и половины от основного отступа (в ресурсный файл dimens.xml). — который из отступов является основным? Индус на ютубе ситуацию как-то не прояснил.

2024-07-22 05:38 UTC, ievetrovdev commented
> Что-то совсем туго пошло. Приложение даже и запускаться не хочет.
> 
> Откуда учитывать нижний отступ для контейнера с кнопками - от края макета или от навбара? Как включить его (навбара) отображение?
> 
> Атрибуты в стиле StyleNavButton android:paddingVertical и android:paddingHorizontal — для внутренних отступов. Не пойму как ими пользоваться.
> 
> Размеры основного отступа и половины от основного отступа (в ресурсный файл dimens.xml). — который из отступов является основным? Индус на ютубе ситуацию как-то не прояснил.

Все в порядке, сейчас разберемся.

2024-07-22 05:40 UTC, ievetrovdev commented
> Откуда учитывать нижний отступ для контейнера с кнопками - от края макета или от навбара? Как включить его (навбара) отображение?

Считаем нижней гранью экрана на макете нарисованный навбар. До него расстояние 8dp. Нарисованный навбар – это имитация устройства и в реальности они могут сильно отличаться друг от друга. Его нельзя включить или выключить, он по умолчанию на всех устройствах в том или ином виде.

2024-07-22 05:41 UTC, ievetrovdev commented
> Атрибуты в стиле StyleNavButton android:paddingVertical и android:paddingHorizontal — для внутренних отступов. Не пойму как ими пользоваться.

Паддинг внутри кнопки добавляет внутренний отступ между текстом кнопки и ее границами.

2024-07-22 05:44 UTC, ievetrovdev commented
> Размеры основного отступа и половины от основного отступа (в ресурсный файл dimens.xml). — который из отступов является основным? Индус на ютубе ситуацию как-то не прояснил.

Как правило в макетах есть самые популярные размеры, которых подавляющее большинство в макете. Их интуитивно можно увидеть и выделить в отдельный ресурс. Например, у нас очень часто встречается расстояние 16dp по бокам экрана или между карточек. Так вот этот размер можно назвать main_space_16. А половину от него, например, так main_space_half_8. Это будет красиво и единообразно.

2024-07-22 05:46 UTC, ievetrovdev commented
> Что-то совсем туго пошло. Приложение даже и запускаться не хочет.

а что пишет? пришли скрины в личку. потому что у меня нормально 03 ветка собирается и запускается

2024-07-22 05:49 UTC, ievetrovdev commented
Важно. Апдейт по иконке самого приложения

Иконку приложения (именно которая будет отображаться на лаунчере, в настройках устройства и т.д.) экспортируем из фигмы как растровое изображение в png.

После этого согласно инструкции импортировать нужно как new image asset. В этом случае студия сгенерирует версии картинки в разных разрешениях в оригинале для разных случаев применения. Все они будут распределены по каталогам с соответствующими квалификаторами.

2024-07-22 05:56 UTC, ievetrovdev requested changes

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/java/com/practicum/recipeapp/MainActivity.kt
> +//        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
Этот код можно вовсе удалить

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +    android:backgroundTint="#F4FAFF"
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginHorizontal="16dp"
и далее тоже

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +
Пустая строка

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +
Не плоди лишние пустые строки, соблюдаем аккуратность и порядок в коде. Кроме того на всякий случай – не забывай применять автоформатирование перед коммитом.

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="statusBar">#F4FAFF</color>
Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="button_categories">КАТЕГОРИИ</string>
Чтобы при глобальном поиске какой-то строки кода не попадали все значения в кучу, которые включают слово category – стоит для идентификатора этой строки сделать какое-то более общее название. Например, так title_categories. Это одна из причин. И в дальнейшем этот ресурс использовать и для заголовка экрана с категориями в шапке.

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="button_categories">КАТЕГОРИИ</string>
Лучше модифицировать текст программно (в коде активити/фрагмента или в атрибутах), чем сразу писать ресурс капсом. Дополнительная нагрузка на локализаторов.

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/values/themes.xml
> +        <item name="android:windowLightStatusBar">true</item>
Хорошо. Точно такой же атрибут нужен и для навбара

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="statusBar">#F4FAFF</color>
Предлагаю для единообразия и лучшей читаемости добавлять постфикс _color к ресурсам цветов

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +    <ImageView
Иконка для кнопки задается не через отдельное изображение, а просто через атрибут `app:icon`. Он применяется непосредственно к кнопке. См. пункт 4 ТЗ.

2024-07-22 05:56 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        <Button
Все отлично по кнопкам, только стоит еще их окрасить соответствующе с помощью атрибута backgroundTint

2024-07-22 17:46 UTC, 4meech commented
Спасибо, стало яснее!

> > Что-то совсем туго пошло. Приложение даже и запускаться не хочет.
> 
> а что пишет? пришли скрины в личку. потому что у меня нормально 03 ветка собирается и запускается

Заработало после перезагрузки

> Паддинг внутри кнопки добавляет внутренний отступ между текстом кнопки и ее границами.

Не понимаю какое значение должно быть у обоих кнопок в этом макете

2024-07-23 11:46 UTC, ievetrovdev requested changes

2024-07-23 11:46 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="buttonFav_color">#E13E3E</color>
Смешивать стили именования нельзя. Либо верблюд, либо змея)

2024-07-23 11:46 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:paddingVertical">10dp</item>
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-07-23 11:46 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="4dp"
И все в ресурсы

2024-07-23 11:46 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginEnd="4dp"
Чтобы размер кнопок и расстояние между ними было максимально симметричным – лучше добавить по 2dp в конце первой и в начале второй кнопки.

2024-07-24 05:20 UTC, ievetrovdev requested changes

2024-07-24 05:20 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dim_220">220dp</dimen>
тут точно нет неиспользуемого кода?

2024-07-24 05:46 UTC, 4meech commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dim_220">220dp</dimen>
Есть :)

2024-07-25 07:56 UTC, ievetrovdev approved these changes

2024-07-25 08:55 UTC, merged