RA-04 fragment added
4meech/RecipeApp pull request #2
Opened 2024-08-17 13:21 UTC by 4meech

2024-08-18 09:59 UTC, ievetrovdev requested changes

2024-08-18 09:59 UTC, ievetrovdev commented on app/src/main/java/com/practicum/recipeapp/MainActivity.kt
> +                add(R.id.mainContainer, categoriesListFragment)
Ты используешь Java метод add/replace из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add() из класса FragmentTransaction.kt. 

Именно для импорта метода add/replace нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

И предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). То есть вся магия должна происходить в одной лямбде.

2024-08-18 09:59 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dim_10">4dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-08-18 09:59 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dim_10">4dp</dimen>
Стиль названия ресурсов в приложении обычно скорее придумывается, чем берется како-либо эталонный стиль. Существуют разные подходы.

Можно в названии писать цифру в конце, которая означает размер, а можно использовать такую структуру, например:
margin_small_x">10dp
margin_small_xx">12dp 
margin_small_xxx">14dp
margin_normal">16dp
margin_normal_x">18dp
margin_normal_xx">20dp
margin_normal_xxx">22dp

2024-08-18 09:59 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="hello_categories_fragment">New Categories List Fragment</string>
Этот текст-заглушка не требует сохранения в ресурсах, он все равно не будет подвержен локализации. Поэтому как временное решение можно просто захардкодить название фрагмента.

2024-08-18 17:27 UTC, 4meech commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dim_10">4dp</dimen>
Понял, спасибо, пока оставим так

2024-08-18 17:31 UTC, 4meech commented
Допускается ли использование binding при передаче идентификаторов экстеншн функциям supportFragmentManager? Например, вместо R.id.mainContainer использовать такую конструкцию:

`supportFragmentManager.commit {
                setReorderingAllowed(true)
                add<CategoriesListFragment>(binding.mainContainer.id)
            }`

2024-08-19 12:18 UTC, ievetrovdev requested changes

2024-08-19 12:18 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Не нужно помечать комментарии как решенные, тем более, что тут изменений нет.

2024-08-19 12:18 UTC, ievetrovdev commented on app/src/main/java/com/practicum/recipeapp/CategoriesListFragment.kt
> +        s: Bundle?
Про стиль и информативность именования переменных обсуждалось на KotlinSprint. Именование одной буквой не является хорошим тоном. Кроме того, когда переопределяешь стандартный метод – все названия переменных проставляются автоматически.

2024-08-20 14:46 UTC, ievetrovdev approved these changes

2024-08-21 09:32 UTC, merged