RA-06 entity data classes
4meech/RecipeApp pull request #4
Opened 2024-08-21 20:45 UTC by 4meech

Уж не знаю намудрил со строками или нет, но уж как получилось :) Наверное всё же стоит озвучивать ход своих мыслей. Почему в getCategories() возвращаю emptyList: если вдруг в последующем придётся в коде использовать возвращаемый этой функцией список, то там гарантированно будет не null, а уже наличие в списке элементов можно проверять методом isEmpty

2024-08-22 19:00 UTC, ievetrovdev requested changes

2024-08-22 19:00 UTC, ievetrovdev commented on app/build.gradle.kts
> +    sourceSets {
что это и зачем?

2024-08-22 19:00 UTC, ievetrovdev commented on app/src/main/java/com/practicum/recipeapp/recipes.kt
> +    fun categoriesInit(context: Context) {
Создай просто список

2024-08-22 19:00 UTC, ievetrovdev commented on app/src/main/java/com/practicum/recipeapp/recipes.kt
> +                    title = context.getString(R.string.cat_burgers_name),
Это замоканный временный список. Ты же не будешь все данные с сервера сохранять локально, убирай все ресурсы

2024-08-22 19:00 UTC, ievetrovdev commented on app/src/main/java/com/practicum/recipeapp/recipes.kt
> +    val method: String,
Смотри внимательно на тип

2024-08-22 19:00 UTC, ievetrovdev commented on app/src/main/java/com/practicum/recipeapp/recipes.kt
> +    val quantity: Double,
Здесь тоже тип отличается

2024-08-22 19:22 UTC, 4meech commented on app/build.gradle.kts
> +    sourceSets {
Понятия не имею, само сгенерилось

2024-08-23 17:46 UTC, ievetrovdev approved these changes

2024-08-23 18:27 UTC, merged