RA-08 RecyclerView list scrolling
4meech/RecipeApp pull request #6
Opened 2024-09-04 20:14 UTC by 4meech

2024-09-05 17:02 UTC, ievetrovdev commented
Сейчас у тебя кнопки навигации наслаиваются на RecyclerView,  нельзя прочитать полностью информацию из последних элементов. Давай лучше ограничем длину RecyclerView по кнопкам

2024-09-05 17:09 UTC, ievetrovdev requested changes
В целом молодец, очень мало замечаний, поправь только эти небольшие и давай переходить дальше

2024-09-05 17:09 UTC, ievetrovdev commented on app/src/main/java/com/practicum/recipeapp/CategoriesListAdapter.kt
> +        return ViewHolder(view)
Давай сразу во viewHolder передавать binding, так код станет более читаемым 
ItemCategoryBinding.inflate(LayoutInflater.from(parent.context), parent, false)

2024-09-07 12:55 UTC, 4meech commented on app/src/main/java/com/practicum/recipeapp/CategoriesListAdapter.kt
> +        return ViewHolder(view)
Не уверен, что верно сделал с binding'ом

2024-09-07 18:20 UTC, ievetrovdev approved these changes
Молодец, с  binding'ом всё сделал правильно. RecyclerView.ViewHolder() на вход требует view, а binding.root возвращает корневую вьюху из XML. Binding просто содержит в себе все сгенерированные ссылки на объекты внутри XML, это ни чем не отличается от прошлой реализации по работе, просто более короткая и удобная запись

2024-09-08 07:01 UTC, merged